#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import logging
from wb_device_manager import serial_bus, logger, main
from wb_modbus import minimalmodbus

if __name__ == "__main__":
    debug_handler = logging.StreamHandler(stream=sys.stdout)
    debug_handler.setLevel(logging.DEBUG)
    debug_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(debug_handler)

    ports = sys.argv[1:]
    main.DeviceManager().scan_serial_bus(*ports)
