#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import logging
from wb.device_manager import logger, main

if __name__ == "__main__":
    debug_handler = logging.StreamHandler(stream=sys.stdout)
    debug_handler.setLevel(logging.DEBUG)
    debug_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(debug_handler)

    main.main()
