#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import logging
from wb_device_manager import serial_bus, logger
from wb_modbus import minimalmodbus

if __name__ == "__main__":
    debug_handler = logging.StreamHandler(stream=sys.stdout)
    debug_handler.setLevel(logging.DEBUG)
    debug_handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))
    logger.addHandler(debug_handler)

    ports = ["/dev/ttyRS485-1",]
    for port in ports:
        try:
            scanner = serial_bus.ExtendedMBusScanner(port)
            scanner.scan_bus()
        except minimalmodbus.MasterReportedException:
            logger.exception("Port: %s", port)
